sudo: required
dist: trusty

script:
  - bash -xve ./test/travis_ros_install.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_package_make.bash
  - source ~/catkin_ws/devel/setup.bash
  - ./test/travis_prepare_dummy_files.bash
  - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
  - rostest pimouse_vision_control test-left-face.launch
  - rostest pimouse_vision_control test-right-face.launch
